package.json, src/main.ts, src/store/index.ts, src/views/Login.vue
Using Lokapi, careful review appreciated !
=> new: using ``lokapi``

src/store/index.ts
There were some small change on LokAPI's API after v0.0.3+ . These are the fixes to remain compatible.
=> fix: compatibility with lokapi 0.0.3+

.github/workflows/deploy.yml, package-lock.json, package.json
Notice I had to delete `package-lock.json`. Would this have any bad consequences ?
The build is done using node 14
The sync will only work after setting the secret private key in the settings of the current github repository.
It'll need to be called `sftp_private_key`.
Also, I couldn't keep the git link to `lokapi` so I pinned the version.
I tested the sync on my fork of `lokavaluto-web-application`.
=> new: pkg: add auto-deploy to ``monujo.dev.lokavaluto.org``

src/store/lokapi.ts
=> new: add support of ``http`` protocol

package.json, src/components/rightCol/ThisWeek.vue, src/components/sendAskMoney/SendAskMoney.vue, src/store/lokapi.ts
Note:
- also removed access to ``jsonData`` this should remain an internal,
there are accessors.
=> fix: dev: compat with lokapi v0.0.13+

package.json, src/components/sendAskMoney/SendAskMoney.vue
Example of implementation of `.searchProRecipient(..)`. This might need some tweaks.
=> new: add pro search payment support

package.json, src/components/Core.vue, src/components/sendAskMoney/SendAskMoney.vue, src/store/index.ts, src/store/lokapi.ts, vue.config.js
There is an addition of `sweetalert2` also.
=> Comchain and new packages

src/assets/main.scss, src/components/Core.vue, src/components/Nav.vue, src/components/core/LeftCol.vue, src/components/core/RightCol.vue, src/components/leftCol/GlobalBal.vue, src/components/leftCol/YourAccs.vue, src/components/rightCol/OperationsSelector.vue, src/components/sendAskMoney/SendAskMoney.vue
=> Fix responsive issues

src/components/Nav.vue, src/router/index.ts, src/store/lokapi.ts, src/views/admin/PendingAccounts.vue
=> Admin pending accounts list 

src/components/CreateAccount.vue, src/components/Nav.vue, src/router/index.ts, src/views/Dashboard.vue, src/views/Login.vue
chg: dev [component] rename the dashboard page from "profile" to
"dashboard" and update all concerned routes and redirects accordingly
Fixes #64, #65
=> Fix lokavaluto logo link to dashboard and dashboard page name

src/components/sendAskMoney/SendAskMoney.vue
...from a currency the current logged in user does not have any account in
Closes #51
=> Fix recipient list search wrongly returning results

.github/workflows/deploy.yml, src/components/Nav.vue, src/router/index.ts, src/services/lokapiService.ts, src/views/Carto.vue
First release of carto implemetation
TODO: a way to have dynamic map url.
=> WIP: [NEW] add carto entry for web and mobile app 

.github/workflows/deploy.yml
fix: carto auto deploy url is not correct.
=> fix: dev: use correct carto url for deploy action

package.json, src/views/Login.vue, vue.config.js
Some changes were made in lokapi to extract some types and exception used by a few packages,
this has an impact in monujo, this is the fix to keep compatibility.
=> chg: dev: update code for compatibility with last ``lokapi-browser``

src/assets/main.scss, src/components/sendAskMoney/SendAskMoney.vue
Improve size, position, and button sizes - positioning of the footer in small screens
Fixes the scrollbar appearing in small screens that we did not want to see there.
Adds a small margin around boxes in small screens.
=> Small creen fixes and space optimizations

.eslintrc.js, babel.config.js, src/App.vue, src/components/Core.vue, src/components/CreateAccount.vue, src/components/Modal.vue, src/components/Nav.vue, src/components/core/LeftCol.vue, src/components/core/RightCol.vue, src/components/leftCol/PayCards.vue, src/components/leftCol/YourAccs.vue, src/components/leftCol/payCards/AddPayCard.vue, src/components/leftCol/payCards/PayCard.vue, src/components/leftCol/yourAccs/Acc.vue, src/components/modal/MyModal.vue, src/components/rightCol/AllTrs.vue, src/components/rightCol/LastWeek.vue, src/components/rightCol/OperationsSelector.vue, src/components/rightCol/ThisWeek.vue, src/components/rightCol/TransactionSubCard.vue, src/components/rightCol/pictos/QRPicto.vue, src/components/rightCol/pictos/TransactionPicto.vue, src/components/sendAskMoney/SendAskMoney.vue, src/main.ts, src/views/Carto.vue, src/views/CreateMyAccount.vue, src/views/Dashboard.vue, src/views/Login.vue, src/views/admin/PendingAccounts.vue, src/views/admin/PendingCredits.vue
This is based on the work done by @vaab here:
https://github.com/Lokavaluto/monujo/pull/63
We must now as a team lint our code before changes.
=> Fix indentation, add lint rules and fix post-logout redirect-route

src/components/core/RightCol.vue, src/components/rightCol/ThisWeek.vue, src/store/index.ts, src/store/lokapi.ts, src/views/Login.vue
This PR builds upon the PR #99 (must be merged *after* #99)
It will fix the (broken) loading of the transactions list upon autologin.
It will implement the infinite scroll behaviour in the transactions list modal.
It will remove the useless transactions type selector at the top of the transactions list.
Resolves #37, resolves #38
=> Transactions list enhancements

src/components/sendAskMoney/SendAskMoney.vue
Will add a second screen when the user clicks on the button explaining that the transactions must be completed before the balance and transactions list are updated.
This screen is visible after clicking on the odoo order link button and when returning to the app.
=> Fix credit workflow after odoo

src/components/leftCol/YourAccs.vue
Will add a refresh button at the top of the accounts list to refresh all data (accounts + transactions)
(closes #9)
=> new: add refresh button on accounts lists

public/config.sample.json, src/components/Nav.vue
Will conditionnally show CGU and Help menu entries in the user dropdown when they are set in the instance config file.
(Closes #116, closes #117)
=> new: add per-instance configurable CGU and help urls

.github/workflows/deploy.yml, public/config.sample.json, src/main.ts, src/services/lokapiService.ts
=> Password timeout

src/components/sendAskMoney/SendAskMoney.vue
This PR will unify the send money modal by removing the choice of pro/part recipient, and using the same method for pro and part recipient searches.
While at it, I took a plunge and removed an useless icon in the recipients list items (issue 85).
( closes #85, closes #119 )
=> Merge pro and part search modals

src/components/Nav.vue
=> Rename the Carto menu entry to Carte

src/components/rightCol/TransactionSubCard.vue
=> Fix long text names overflowing the transactions list

.github/workflows/deploy.yml, public/config.sample.json, src/components/Nav.vue, src/views/Login.vue
This will make the app logo configurable in a the config.js file.
=> chg: make the logo configurable per-instance

src/assets/custom-variables.scss, src/assets/main.scss, src/components/core/RightCol.vue, src/components/rightCol/AllTrs.vue, src/components/sendAskMoney/SendAskMoney.vue, src/services/lokapiService.ts
=> fix: adjust modals height and width according to content (fixes #20)

src/assets/main.scss, src/components/leftCol/YourAccs.vue, src/store/lokapi.ts
Add loader in case of : 
-reloading the page
-clicking on the refresh button
-login
=> new: add loader to the accounts vue

src/assets/main.scss, src/components/core/RightCol.vue, src/components/rightCol/ThisWeek.vue, src/store/lokapi.ts
Showing the loader in case of : 
- refreshing the page
- clicking on the refresh button
- login
=> new: add loader to transactions list

src/assets/custom-variables.scss, src/assets/main.scss, src/components/Nav.vue, src/components/leftCol/yourAccs/Acc.vue, src/components/sendAskMoney/SendAskMoney.vue
Needs to merge #140 before this one.
* enable accounts list deep style customization
* enable individual bottom bar buttons customization
* enable top-bar background and menu items customization
=> Add style customization capabilities (based on #140)

src/components/CreateAccount.vue
=> fix: trigger createUserAccount by pushing enter button (fixes #46)

src/assets/main.scss, src/components/leftCol/YourAccs.vue, src/components/rightCol/ThisWeek.vue, src/store/lokapi.ts
Fix their behaviour so they are consistent in case of server error.
Make them look-alike (use same CSS classes for messages, fix margins)
This will allow us to handle the server errors gracefully.
=> Rework transactions and accounts loader/loading logic

src/assets/custom-variables.scss
=> Menu items should have white background by default

src/components/sendAskMoney/SendAskMoney.vue
=> new: preselect amount to be credited (fixes #11)

src/views/admin/PendingCredits.vue
It will close the issue #73. SeddikKadi took care of the other elements referenced. The only one missing was this one.
(Closes #73)
=> Add pending credits request loading indicator (based on #155)

src/components/core/RightCol.vue
=> Fix exception thrown on transactions modal close

src/views/Login.vue
=> fix: remove white spaces in login before sending it (fixes: #176)

src/assets/main.scss, src/components/core/RightCol.vue, src/components/sendAskMoney/SendAskMoney.vue
=> fix: make modal title shrink and fix arrow icon position (foxes: #173)

package-lock.json
Includes most notably ``jsc3l`` in version ``2.0.1-rc.5`` that will
throw an exception upon blockchain API errors and allow correct
behavior to handle the issue for upper layers as lokapi or monujo.
=> fix: pkg: updated to last packages

package-lock.json
Updated packages, including ``@lokavaluto/lokapi-backend-comchain``
in version ``0.0.2-alpha.202204141158`` which corrects the issue.
=> fix: display source user for incoming comchain transactions

src/views/admin/PendingAccounts.vue, src/views/admin/PendingCredits.vue
=> fix: make pending credits table responsive (fixes: #184)

src/components/Nav.vue
=> Admin menus in main menu

src/components/sendAskMoney/SendAskMoney.vue
=> Put the modal action buttons in their respective modal footers

src/assets/main.scss, src/components/core/RightCol.vue, src/store/lokapi.ts
=> new: add loader to transaction list (fixes: #174)

package-lock.json
=> fix: pkg: upgrade versions to remove vulnerability and fix transaction related user display (fixes #194)

src/App.vue, src/assets/main.scss, src/components/core/RightCol.vue, src/components/sendAskMoney/SendAskMoney.vue, src/store/index.ts
=> fix: prevent scroll underneath modals (fixes: #181)

src/components/sendAskMoney/SendAskMoney.vue
=> fix: avoid null ref error on purchase money (fixes: #199)

src/assets/main.scss, src/views/admin/PendingAccounts.vue, src/views/admin/PendingCredits.vue
Displays loader while validating pending credits and accounts
=> Validation credit loader and account loader

src/components/sendAskMoney/SendAskMoney.vue
=> fix: add placeholder to amount send money field (fixes: #221)

package-lock.json, src/components/sendAskMoney/SendAskMoney.vue
Please note that a PR ( https://github.com/com-chain/api/pull/19 ) is required on comchain side to fully test
this on the comchain currency.
The package.json was updated and need packages from lokapi and depdencies that will bring also the new ``fetch()`` http request facility. I recommend to apply first the other PR #214 introducing this, and to rebase this one after to keep things clean and tidy.
=> fix: add error popup upon payment with insufficient balance

src/components/leftCol/YourAccs.vue
=> new: add create account link in case no wallet found (fixes: #227)

src/components/CreateAccount.vue, src/components/sendAskMoney/SendAskMoney.vue, src/main.ts, src/services/toastService.ts
this PR is based on #216 only the last commit needs to be reviewed
=> Enforce common notification system everywhere

package-lock.json, src/main.ts, src/views/Login.vue
=> new: fill email with last email provided (fixes: #237)

src/assets/main.scss, src/views/Login.vue
=> new: add create account and reset password buttons (fixes: #224)

.github/workflows/deploy.yml, public/config.sample.json, public/index.html, src/components/Core.vue, src/components/CreateAccount.vue, src/main.ts, src/router/index.ts, src/services/lokapiService.ts
This is a rewrite of #242 and benefits from previous comments and reviews of this latter PR
=> make app name configurable through ``config.json``

src/assets/main.scss, src/components/CreateAccount.vue
Based on ( PR #236 ) 
( closes: #240 )
=> Rework wallet creation style

src/assets/main.scss, src/components/MoneyCreditModal.vue, src/components/MoneyTransferModal.vue, src/components/PartnerItem.vue, src/components/SendAskMoney.vue, src/components/TheDashboardFooter.vue, src/store/lokapi.ts, src/views/Dashboard.vue
- Refactor ``SendAskMoney`` component into two components with clear responsibilities
- Enhance modal's headers
- Enhance send money workflow by removing redundant recipient naming and providing feedback to the user
- Refactor partner item into its own ``PartnerItem`` component
=> Refactor sendaskmoney into separate modals components, partner item into a separate component

src/components/TheNavBar.vue
=> Move support buttons so that unconnected user can access them

src/components/MoneyTransferModal.vue
provide a fix related to updating search recipient list on user typing.
=> fix: Fix search recipient on android devices

src/components/BankAccountItem.vue, src/components/CreateAccount.vue, src/components/TheBankAccountList.vue, src/components/TheNavBar.vue, src/components/TheTransactionList.vue, src/components/TransactionListFull.vue, src/components/TransactionListRecent.vue, src/utils/vuex.ts
=> chg: dev: replace all getters by mapGetter and mapState (fixes #290)

src/assets/main.scss, src/components/CreateAccount.vue, src/components/MoneyTransferModal.vue, src/components/TheBankAccountList.vue, src/components/TheNavBar.vue, src/store/lokapi.ts
Following the technical `mapGetter` fix, some functionality were broken.
A few small fixes were also made.
=> Fix create account

src/assets/main.scss, src/components/ConfirmPaymentModal.vue, src/components/MoneyCreditModal.vue, src/components/PendingTopUp.vue, src/components/TheBankAccountList.vue, src/components/TheTransactionList.vue, src/components/TransactionItem.vue, src/components/TransactionListRecent.vue, src/i18n/fr-FR/app.po, src/views/Dashboard.vue
=> new: add pending topups to dashboard
